### ISSUE TITLE
First serve step in tutorial doesn't work?

### ISSUE THREAD

**Issue by moshen** [andreypopp/sitegen#21]
Step "DEVELOPMENT SERVER" on https://andreypopp.github.io/sitegen/tutorial produces this error:

```
ERROR in ./~/sitegen/lib/loader/boot.js!./sitegen.config.js
Module build failed: Invariant Violation: Unknown route: [object Object]
    at invariant (/Users/moshen/code/sitegen-test/node_modules/invariant/invariant.js:42:15)
    at RouteCompiler._render (/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/routing/RouteCompiler.js:177:33)
    at RouteCompiler.render (/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/routing/RouteCompiler.js:164:19)
    at Object.bootLoader (/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/loader/boot.js:51:17)
 @ multi main
webpack: bundle is now VALID.
Unhandled rejection Error: Cannot find module "/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/loader/boot.js!/Users/moshen/code/sitegen-test/sitegen.config.js"
    at webpackMissingModule (<boot>:588:43)
    at Object.<anonymous> (<boot>:588:217)
    at __webpack_require__ (<boot>:556:30)
    at <boot>:579:37
    at <boot>:582:10
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at module.exports (/Users/moshen/code/sitegen-test/node_modules/eval/eval.js:62:12)
    at evalAsModule (/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/compiler/utils.js:59:29)
    at evalBundle (/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/compiler/utils.js:37:12)
```

Yes, `sitegen.config.js` exists in the folder specified.

Running node v6.3.0.

**Comment by andreypopp** [comment]
Could you post your `sitegen.config.js`?

**Comment by andreypopp** [comment]
Oh, I didn't update tutorial for the recent version, please see https://github.com/andreypopp/sitegen/blob/master/site/sitegen.config.js (sitegen site config) for the usage.

**Comment by moshen** [comment]
Might need to update your tutorial further.  After changing the `sitegen.config.js` to:

```
import {page} from 'sitegen/routing';

export let route = page('./components/Site', undefined, {
  index: page('./index.js', {split: true}),
});
```

```
ERROR in ./~/sitegen/lib/loader/boot.js!./sitegen.config.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components/Site in /Users/moshen/code/sitegen-test
 @ ./~/sitegen/lib/loader/boot.js!./sitegen.config.js 11:13-41

ERROR in ./~/sitegen/lib/loader/boot.js!./sitegen.config.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./components/Site in /Users/moshen/code/sitegen-test
 @ ./~/sitegen/lib/loader/boot.js!./sitegen.config.js 27:8-115
webpack: bundle is now VALID.
Unhandled rejection Error: Cannot find module "/Users/moshen/code/sitegen-test/node_modules/sitegen/lib/loader/meta.js!./components/Site"
    at webpackMissingModule (eval at <anonymous> (<boot>:3529:2), <anonymous>:27:73)
    at eval (eval at <anonymous> (<boot>:3529:2), <anonymous>:27:246)
    at Object.<anonymous> (<boot>:3529:2)
    at __webpack_require__ (<boot>:556:30)
    at fn (<boot>:87:20)
    at Object.<anonymous> (<boot>:588:19)
    at __webpack_require__ (<boot>:556:30)
    at <boot>:579:37
    at <boot>:582:10
    at ContextifyScript.Script.runInContext (vm.js:35:29)
```

Not sure what `components/Site` is supposed to be.

**Comment by ghostsquad** [comment]
Has this been resolved?

**Comment by moshen** [comment]
I gave up and rolled something with [Metalsmith](http://www.metalsmith.io/) so I have no idea.
